require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pays", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Pay. As you add validations to Pay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Pay.create! valid_attributes
      get pays_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pay = Pay.create! valid_attributes
      get pay_url(pay)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pay_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      pay = Pay.create! valid_attributes
      get edit_pay_url(pay)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Pay" do
        expect {
          post pays_url, params: { pay: valid_attributes }
        }.to change(Pay, :count).by(1)
      end

      it "redirects to the created pay" do
        post pays_url, params: { pay: valid_attributes }
        expect(response).to redirect_to(pay_url(Pay.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Pay" do
        expect {
          post pays_url, params: { pay: invalid_attributes }
        }.to change(Pay, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pays_url, params: { pay: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pay" do
        pay = Pay.create! valid_attributes
        patch pay_url(pay), params: { pay: new_attributes }
        pay.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pay" do
        pay = Pay.create! valid_attributes
        patch pay_url(pay), params: { pay: new_attributes }
        pay.reload
        expect(response).to redirect_to(pay_url(pay))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pay = Pay.create! valid_attributes
        patch pay_url(pay), params: { pay: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pay" do
      pay = Pay.create! valid_attributes
      expect {
        delete pay_url(pay)
      }.to change(Pay, :count).by(-1)
    end

    it "redirects to the pays list" do
      pay = Pay.create! valid_attributes
      delete pay_url(pay)
      expect(response).to redirect_to(pays_url)
    end
  end
end
